-- ADC Platform Admin Dashboard Schema v2.2
-- Execute this script in Supabase SQL Editor

-- 1. Extensions & Utilities
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Users & Profiles
DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM ('admin', 'user');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  name TEXT,
  role public.user_role NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure columns exist if table already exists
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role public.user_role NOT NULL DEFAULT 'user';

DROP TRIGGER IF EXISTS trg_profiles_updated_at ON public.profiles;
CREATE TRIGGER trg_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 3. Audit Logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id UUID REFERENCES public.profiles(id),
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON public.audit_logs(created_at DESC);

-- 4. Connectors
CREATE TABLE IF NOT EXISTS public.connectors (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  is_enabled BOOLEAN DEFAULT TRUE,
  config JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_connectors_updated_at ON public.connectors;
CREATE TRIGGER trg_connectors_updated_at
BEFORE UPDATE ON public.connectors
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 5. Connector Runs (Job Queue)
CREATE TABLE IF NOT EXISTS public.connector_runs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  connector_id UUID REFERENCES public.connectors(id),
  status TEXT DEFAULT 'queued',
  attempt INT NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMPTZ,
  locked_by TEXT,
  locked_at TIMESTAMPTZ,
  priority INT DEFAULT 0,
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  stats JSONB,
  error_json JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure columns exist for Job Queue if table already exists
ALTER TABLE public.connector_runs ADD COLUMN IF NOT EXISTS attempt INT NOT NULL DEFAULT 0;
ALTER TABLE public.connector_runs ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMPTZ;
ALTER TABLE public.connector_runs ADD COLUMN IF NOT EXISTS locked_by TEXT;
ALTER TABLE public.connector_runs ADD COLUMN IF NOT EXISTS locked_at TIMESTAMPTZ;
ALTER TABLE public.connector_runs ADD COLUMN IF NOT EXISTS priority INT DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_connector_runs_status_created ON public.connector_runs(status, created_at DESC);

-- 6. Design Runs
CREATE TABLE IF NOT EXISTS public.design_runs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  run_type TEXT NOT NULL,
  status TEXT DEFAULT 'queued',
  created_by UUID REFERENCES public.profiles(id),
  input_json JSONB,
  progress INT DEFAULT 0,
  attempt INT NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMPTZ,
  locked_by TEXT,
  locked_at TIMESTAMPTZ,
  error_json JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure columns exist for Job Queue if table already exists
ALTER TABLE public.design_runs ADD COLUMN IF NOT EXISTS attempt INT NOT NULL DEFAULT 0;
ALTER TABLE public.design_runs ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMPTZ;
ALTER TABLE public.design_runs ADD COLUMN IF NOT EXISTS locked_by TEXT;
ALTER TABLE public.design_runs ADD COLUMN IF NOT EXISTS locked_at TIMESTAMPTZ;

-- Ensure created_by exists (Fix for error 42703)
ALTER TABLE public.design_runs ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES public.profiles(id);

DROP TRIGGER IF EXISTS trg_design_runs_updated_at ON public.design_runs;
CREATE TRIGGER trg_design_runs_updated_at
BEFORE UPDATE ON public.design_runs
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_design_runs_status_created ON public.design_runs(status, created_at DESC);

-- 7. Reports
CREATE TABLE IF NOT EXISTS public.reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  run_id UUID NOT NULL REFERENCES public.design_runs(id) ON DELETE CASCADE,
  report_json JSONB NOT NULL,
  claim_evidence_rate NUMERIC,
  assumption_count INT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. Report Artifacts
CREATE TABLE IF NOT EXISTS public.report_artifacts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  run_id UUID NOT NULL REFERENCES public.design_runs(id) ON DELETE CASCADE,
  artifact_type TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  content_type TEXT,
  size_bytes BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. Alerts
CREATE TABLE IF NOT EXISTS public.alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,                 -- error, warning, info
  source TEXT NOT NULL,               -- connector, worker, system
  message TEXT NOT NULL,
  details JSONB,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_created ON public.alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_is_read ON public.alerts(is_read) WHERE is_read = FALSE;

-- 9. Security (RLS)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$ LANGUAGE sql STABLE;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.connectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.connector_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.design_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- Policies
-- Profiles
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;
CREATE POLICY "Admins can view all profiles" ON public.profiles FOR SELECT USING (public.is_admin());

-- Admin Only Tables
DROP POLICY IF EXISTS "Admins full access connectors" ON public.connectors;
CREATE POLICY "Admins full access connectors" ON public.connectors FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins full access connector_runs" ON public.connector_runs;
CREATE POLICY "Admins full access connector_runs" ON public.connector_runs FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins full access audit_logs" ON public.audit_logs;
CREATE POLICY "Admins full access audit_logs" ON public.audit_logs FOR ALL USING (public.is_admin());

-- Design Runs & Reports
DROP POLICY IF EXISTS "Users view own runs" ON public.design_runs;
CREATE POLICY "Users view own runs" ON public.design_runs FOR SELECT USING (auth.uid() = created_by);

DROP POLICY IF EXISTS "Users create runs" ON public.design_runs;
CREATE POLICY "Users create runs" ON public.design_runs FOR INSERT WITH CHECK (auth.uid() = created_by);

DROP POLICY IF EXISTS "Admins view all runs" ON public.design_runs;
CREATE POLICY "Admins view all runs" ON public.design_runs FOR SELECT USING (public.is_admin());

DROP POLICY IF EXISTS "Users view own reports" ON public.reports;
CREATE POLICY "Users view own reports" ON public.reports FOR SELECT USING (EXISTS (SELECT 1 FROM public.design_runs WHERE id = reports.run_id AND created_by = auth.uid()));

DROP POLICY IF EXISTS "Admins view all reports" ON public.reports;
CREATE POLICY "Admins view all reports" ON public.reports FOR SELECT USING (public.is_admin());

DROP POLICY IF EXISTS "Users view own artifacts" ON public.report_artifacts;
CREATE POLICY "Users view own artifacts" ON public.report_artifacts FOR SELECT USING (EXISTS (SELECT 1 FROM public.design_runs WHERE id = report_artifacts.run_id AND created_by = auth.uid()));

DROP POLICY IF EXISTS "Admins view all artifacts" ON public.report_artifacts;
CREATE POLICY "Admins view all artifacts" ON public.report_artifacts FOR SELECT USING (public.is_admin());

-- Alerts
DROP POLICY IF EXISTS "Admins full access alerts" ON public.alerts;
CREATE POLICY "Admins full access alerts" ON public.alerts FOR ALL USING (public.is_admin());
