"""
Golden Seed Manual Loading Script
문서의 20개 ADC Seed를 golden_seed_items 테이블에 직접 적재합니다.

Usage:
    cd services/engine
    python load_golden_seeds.py
"""

import os
from supabase import create_client
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

# 20개 ADC Seed 데이터 (Golden Set Seed 수동추가.md 기반)
GOLDEN_SEEDS = [
    # ========== Group A (Approved) - 10개 ==========
    {
        "drug_name_canonical": "Trastuzumab deruxtecan",
        "aliases": "Enhertu|DS-8201",
        "portfolio_group": "Group A (Approved)",
        "target": "HER2",
        "antibody": "Trastuzumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Topo1 inhibitor",
        "payload_exact_name": "DXd",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "ILD (Interstitial Lung Disease)",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 761139",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Trastuzumab emtansine",
        "aliases": "Kadcyla|T-DM1",
        "portfolio_group": "Group A (Approved)",
        "target": "HER2",
        "antibody": "Trastuzumab",
        "linker_family": "Non-cleavable",
        "linker_trigger": "N/A",
        "payload_family": "Microtubule inh",
        "payload_exact_name": "DM1 (Maytansinoid)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Thrombocytopenia",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 125427",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Brentuximab vedotin",
        "aliases": "Adcetris|SGN-35",
        "portfolio_group": "Group A (Approved)",
        "target": "CD30",
        "antibody": "Brentuximab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Microtubule inh",
        "payload_exact_name": "MMAE (Auristatin)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Peripheral Neuropathy",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 125388",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Sacituzumab govitecan",
        "aliases": "Trodelvy|IMMU-132",
        "portfolio_group": "Group A (Approved)",
        "target": "TROP2",
        "antibody": "Sacituzumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Acid-labile (pH)",
        "payload_family": "Topo1 inhibitor",
        "payload_exact_name": "SN-38",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Severe Diarrhea / Neutropenia",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 761115",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Enfortumab vedotin",
        "aliases": "Padcev|ASG-22ME",
        "portfolio_group": "Group A (Approved)",
        "target": "Nectin-4",
        "antibody": "Enfortumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Microtubule inh",
        "payload_exact_name": "MMAE (Auristatin)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Skin reactions (SJS/TEN)",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 761144",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Polatuzumab vedotin",
        "aliases": "Polivy",
        "portfolio_group": "Group A (Approved)",
        "target": "CD79b",
        "antibody": "Polatuzumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Microtubule inh",
        "payload_exact_name": "MMAE (Auristatin)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Peripheral Neuropathy",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 761121",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Tisotumab vedotin",
        "aliases": "Tivdak",
        "portfolio_group": "Group A (Approved)",
        "target": "Tissue Factor",
        "antibody": "Tisotumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Microtubule inh",
        "payload_exact_name": "MMAE (Auristatin)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Ocular Toxicity",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 761208",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Loncastuximab tesirine",
        "aliases": "Zynlonta|ADCT-402",
        "portfolio_group": "Group A (Approved)",
        "target": "CD19",
        "antibody": "Loncastuximab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "DNA alkylator",
        "payload_exact_name": "SG3199 (PBD dimer)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Edema / Effusion",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 761169",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Mirvetuximab soravtansine",
        "aliases": "Elahere|IMGN853",
        "portfolio_group": "Group A (Approved)",
        "target": "FR alpha",
        "antibody": "Mirvetuximab",
        "linker_family": "Cleavable",
        "linker_trigger": "Disulfide (Redox)",
        "payload_family": "Microtubule inh",
        "payload_exact_name": "DM4 (Maytansinoid)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Ocular Toxicity",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 761310",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Gemtuzumab ozogamicin",
        "aliases": "Mylotarg",
        "portfolio_group": "Group A (Approved)",
        "target": "CD33",
        "antibody": "Gemtuzumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Acid-labile (Hydrazone)",
        "payload_family": "DNA breaker",
        "payload_exact_name": "Calicheamicin",
        "proxy_smiles_flag": False,
        "clinical_phase": "Approved",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "VOD (Veno-occlusive disease)",
        "primary_source_type": "FDA Label",
        "primary_source_id": "BLA 761060",
        "gate_status": "draft",
    },
    # ========== Group B (Late) - 6개 ==========
    {
        "drug_name_canonical": "Datopotamab deruxtecan",
        "aliases": "Dato-DXd|DS-1062",
        "portfolio_group": "Group B (Late)",
        "target": "TROP2",
        "antibody": "Datopotamab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Topo1 inhibitor",
        "payload_exact_name": "DXd",
        "proxy_smiles_flag": False,
        "clinical_phase": "Phase 3",
        "program_status": "Active",
        "outcome_label": "Uncertain",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Stomatitis / Mucositis",
        "primary_source_type": "Clinical Trial",
        "primary_source_id": "NCT04656652",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Patritumab deruxtecan",
        "aliases": "HER3-DXd|U3-1402",
        "portfolio_group": "Group B (Late)",
        "target": "HER3",
        "antibody": "Patritumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Topo1 inhibitor",
        "payload_exact_name": "DXd",
        "proxy_smiles_flag": False,
        "clinical_phase": "Phase 3",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Thrombocytopenia",
        "primary_source_type": "Clinical Trial",
        "primary_source_id": "NCT04619004",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Sacituzumab tirumotecan",
        "aliases": "MK-2870|SKB264",
        "portfolio_group": "Group B (Late)",
        "target": "TROP2",
        "antibody": "Sacituzumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Hydrolysable (Sulfonyl)",
        "payload_family": "Topo1 inhibitor",
        "payload_exact_name": "Belotecan derivative",
        "proxy_smiles_flag": True,
        "proxy_reference": "Belotecan core",
        "clinical_phase": "Phase 3",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Hematologic Toxicity",
        "primary_source_type": "Review Paper",
        "primary_source_id": "PMID: 38245678",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Telisotuzumab vedotin",
        "aliases": "Teliso-V|ABBV-399",
        "portfolio_group": "Group B (Late)",
        "target": "c-Met",
        "antibody": "Telisotuzumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Microtubule inh",
        "payload_exact_name": "MMAE (Auristatin)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Phase 3",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Neuropathy",
        "primary_source_type": "Clinical Trial",
        "primary_source_id": "NCT05029882",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "ABBV-400",
        "aliases": "ABBV-400",
        "portfolio_group": "Group B (Late)",
        "target": "c-Met",
        "antibody": "AbbVie mAb",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Top1 linker)",
        "payload_family": "Topo1 inhibitor",
        "payload_exact_name": "Top1i novel",
        "proxy_smiles_flag": True,
        "proxy_reference": "SN-38 core",
        "clinical_phase": "Phase 2",
        "program_status": "Active",
        "outcome_label": "Uncertain",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Anemia",
        "primary_source_type": "Clinical Trial",
        "primary_source_id": "NCT06084481",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Trastuzumab duocarmazine",
        "aliases": "SYD985",
        "portfolio_group": "Group B (Late)",
        "target": "HER2",
        "antibody": "Trastuzumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "DNA alkylator",
        "payload_exact_name": "Duocarmycin",
        "proxy_smiles_flag": True,
        "proxy_reference": "Seco-DUBA",
        "clinical_phase": "Phase 3",
        "program_status": "Active",
        "outcome_label": "Caution",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Ocular Toxicity",
        "primary_source_type": "Review Paper",
        "primary_source_id": "PMID: 37185211",
        "gate_status": "draft",
    },
    # ========== Group C (Novelty) - 2개 ==========
    {
        "drug_name_canonical": "BL-B01D1",
        "aliases": "BL-B01D1|EGFRxHER3 ADC",
        "portfolio_group": "Group C (Novelty)",
        "target": "EGFR / HER3",
        "antibody": "Bispecific mAb",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Topo1 inhibitor",
        "payload_exact_name": "Ed-04 (Exatecan deriv)",
        "proxy_smiles_flag": True,
        "proxy_reference": "Exatecan core",
        "clinical_phase": "Phase 3",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "CMC",
        "key_risk_signal": "Bispecific Manufacturing Complexity",
        "primary_source_type": "Clinical Trial",
        "primary_source_id": "NCT05983488",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Farletuzumab ecteribulin",
        "aliases": "MORAb-202",
        "portfolio_group": "Group C (Novelty)",
        "target": "FR alpha",
        "antibody": "Farletuzumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "Microtubule inh",
        "payload_exact_name": "Eribulin",
        "proxy_smiles_flag": False,
        "clinical_phase": "Phase 2",
        "program_status": "Active",
        "outcome_label": "Success",
        "key_risk_category": "Efficacy",
        "key_risk_signal": "Lung Toxicity (Low grade)",
        "primary_source_type": "Review Paper",
        "primary_source_id": "PMID: 38814723",
        "gate_status": "draft",
    },
    # ========== Group D (Discontinued) - 2개 ==========
    {
        "drug_name_canonical": "Rovalpituzumab tesirine",
        "aliases": "Rova-T|SC16LD6.5",
        "portfolio_group": "Group D (Discontinued)",
        "target": "DLL3",
        "antibody": "Rovalpituzumab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "DNA alkylator",
        "payload_exact_name": "Tesirine (PBD dimer)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Phase 3",
        "program_status": "Terminated",
        "outcome_label": "Fail",
        "key_risk_category": "Toxicity",
        "key_risk_signal": "Severe Effusion / Sepsis",
        "failure_mode": "Toxicity",
        "primary_source_type": "Clinical Trial",
        "primary_source_id": "NCT01901653",
        "gate_status": "draft",
    },
    {
        "drug_name_canonical": "Vadastuximab talirine",
        "aliases": "SGN-CD33A",
        "portfolio_group": "Group D (Discontinued)",
        "target": "CD33",
        "antibody": "Vadastuximab",
        "linker_family": "Cleavable",
        "linker_trigger": "Protease (Cathepsin)",
        "payload_family": "DNA alkylator",
        "payload_exact_name": "PBD dimer (SGD-1882)",
        "proxy_smiles_flag": False,
        "clinical_phase": "Phase 3",
        "program_status": "Terminated",
        "outcome_label": "Fail",
        "key_risk_category": "Safety",
        "key_risk_signal": "Patient Death (AML)",
        "failure_mode": "Safety",
        "primary_source_type": "Clinical Trial",
        "primary_source_id": "NCT02785900",
        "gate_status": "draft",
    },
]


def load_seeds():
    """Load 20 ADC seeds to golden_seed_items table"""
    if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
        print("Error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set")
        return

    supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)

    print(f"Loading {len(GOLDEN_SEEDS)} seeds to golden_seed_items...")

    success_count = 0
    error_count = 0

    for seed in GOLDEN_SEEDS:
        try:
            # Upsert by drug_name_canonical
            result = (
                supabase.table("golden_seed_items")
                .upsert(seed, on_conflict="drug_name_canonical")
                .execute()
            )

            if result.data:
                success_count += 1
                print(f"  ✓ {seed['drug_name_canonical']}")
            else:
                error_count += 1
                print(f"  ✗ {seed['drug_name_canonical']} - No data returned")

        except Exception as e:
            error_count += 1
            print(f"  ✗ {seed['drug_name_canonical']} - Error: {e}")

    print(f"\nComplete: {success_count} success, {error_count} errors")


if __name__ == "__main__":
    load_seeds()
